OPTIONS (SKIP=1)
LOAD DATA
INTO TABLE "ODBCAPTURE"."GRBTST_JSON"
APPEND
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (ID                             FLOAT EXTERNAL
   ,JSON_DATA                      CHAR(1048576)
   )
