OPTIONS (SKIP=1)
LOAD DATA
INTO TABLE "ODBCAPTURE"."GRBTST_$NAME"
APPEND
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (C1                             CHAR(20)
   ,ID                             FLOAT EXTERNAL
   )
