
insert into "ODBCAPTURE"."BUILD_CONF" ("BUILD_SEQ","BUILD_TYPE","NOTES")
   values (59,'grbxrep','Oracle XDB Repository');

insert into "ODBCAPTURE"."BUILD_PATH" ("PARENT_BUILD_SEQ","BUILD_SEQ")
   values (-82,-59);
insert into "ODBCAPTURE"."BUILD_PATH" ("PARENT_BUILD_SEQ","BUILD_SEQ")
   values (-59,-50);

update "ODBCAPTURE"."ELEMENT_CONF" set "PRE_COMPILE" = 'Y' where "ELEMENT_NAME" = 'VIEW';
-- From Sequence:
--320,"DATA_LOAD"
--330,"TABLE_INDEX"
--350,"MVIEW_INDEX"
--360,"VIEW"
--370,"MVIEW"
update "ODBCAPTURE"."ELEMENT_CONF" set "ELEMENT_SEQ" = 300 where "ELEMENT_NAME" = 'MVIEW';
update "ODBCAPTURE"."ELEMENT_CONF" set "ELEMENT_SEQ" = 370 where "ELEMENT_NAME" = 'MVIEW_INDEX';
update "ODBCAPTURE"."ELEMENT_CONF" set "ELEMENT_SEQ" = 350 where "ELEMENT_NAME" = 'DATA_LOAD';
update "ODBCAPTURE"."ELEMENT_CONF" set "ELEMENT_SEQ" = 320 where "ELEMENT_NAME" = 'VIEW';
update "ODBCAPTURE"."ELEMENT_CONF" set "ELEMENT_SEQ" = 360 where "ELEMENT_NAME" = 'TABLE_INDEX';
update "ODBCAPTURE"."ELEMENT_CONF" set "ELEMENT_SEQ" = 330 where "ELEMENT_NAME" = 'MVIEW';
-- To Sequence:
--320,"VIEW"
--330,"MVIEW"
--350,"DATA_LOAD"
--360,"TABLE_INDEX"
--370,"MVIEW_INDEX"
insert into "ODBCAPTURE"."ELEMENT_CONF" ("ELEMENT_SEQ","ELEMENT_NAME","FILE_EXT1","FILE_EXT2","FILE_EXT3","OBJECT_TYPE","NAME_CHECK_OBJECT_TYPE","NOTES","PRE_COMPILE")
   values (-127,'XDB_ACL','xacl',,,,,'SYS Only. XDB Repositoty ACL (Deprecated) (Not Implemented)',);
insert into "ODBCAPTURE"."ELEMENT_CONF" ("ELEMENT_SEQ","ELEMENT_NAME","FILE_EXT1","FILE_EXT2","FILE_EXT3","OBJECT_TYPE","NAME_CHECK_OBJECT_TYPE","NOTES","PRE_COMPILE")
   values (100,'XML_SCHEMA','pxsd',,,'XML SCHEMA',,'DBMS_XMLSCHEMA Registered Schema (Deprecated)',);

delete from "ODBCAPTURE"."ROLE_CONF" where "ROLENAME" = 'AUTHENTICATEDUSER';
delete from "ODBCAPTURE"."ROLE_CONF" where "ROLENAME" = 'XDBADMIN';
delete from "ODBCAPTURE"."ROLE_CONF" where "ROLENAME" = 'XDB_SET_INVOKER';
delete from "ODBCAPTURE"."ROLE_CONF" where "ROLENAME" = 'XDB_WEBSERVICES';
delete from "ODBCAPTURE"."ROLE_CONF" where "ROLENAME" = 'XDB_WEBSERVICES_WITH_PUBLIC';

delete from "ODBCAPTURE"."SCHEMA_CONF" where "USERNAME" = 'ANONYMOUS';
delete from "ODBCAPTURE"."SCHEMA_CONF" where "USERNAME" = 'XDB';
